// ============================================
// Build script — generates js/config.js from env vars
// Run automatically by Vercel before each deployment
// ============================================
const fs = require('fs');

const url = process.env.SUPABASE_URL;
const key = process.env.SUPABASE_ANON_KEY;

if (!url || !key) {
  console.error('❌ Missing SUPABASE_URL or SUPABASE_ANON_KEY env vars');
  process.exit(1);
}

const content = `// Auto-generated by build.js at deploy time — do not edit or commit
window.__SUPABASE_URL__ = '${url}';
window.__SUPABASE_ANON_KEY__ = '${key}';
`;

fs.writeFileSync('js/config.js', content);
console.log('✅ js/config.js generated from environment variables');
